### ISSUE TITLE
Resarch how TSBPD time differences are implemented

### ISSUE THREAD

**Issue by russelltg** [russelltg/srt-rs#1]
One issue in TSBPD is knowing how to gague when to release packets, which requires somehow syncing clocks on both sides. 

Important snippets of code from reference impl: [a](https://github.com/Haivision/srt/blob/64184c370ba5b0915513bb8c7d10832425c2416d/srtcore/buffer.cpp#L1407)

**Comment by robertream** [comment]
@russelltg the two pull requests I submitted include an implementation of clock sync. From digging through the reference implementation and I discovered it's a bit of a hack, it doesn't wait for a period of stable statistics, erratic network latency could make the clock adjustments erratic. I implemented a drift deviation tolerance. You can close this issue.
