### ISSUE TITLE
Research SYN cookies

### ISSUE THREAD

**Issue by russelltg** [russelltg/srt-rs#10]
Right now it just hashes the peer address, which is potentially wrong.

**Comment by howlowck** [comment]
I'm new to SRT, but according to their [technical overview overview](https://www.haivision.com/resources/white-paper/srt-protocol-technical-overview/). the cookie is a MD5 hash "based on host, port and current time with 1 minute accuracy".

**Comment by russelltg** [comment]
This has been implemented for a while now
