### ISSUE TITLE
Make DuplexConnection responsible for returning handshakes

### ISSUE THREAD

**Issue by russelltg** [russelltg/srt-rs#104]
Should be easy, will require thinking about how DuplexConnection sends packets.

**Comment by robertream** [comment]
I might agree, but why do you feel this is important? Is it a matter of design esthetics?

Regarding how packets are sent, I was expecting to eventually revisit this, but I want to avoid reintroducing async/await into the protocol code, so absent  something like generalized co-routines or effect types becoming available in the language. I suspect that the only way to do this then, is to invert control over the send buffers. This would also have the beneficial effect of getting us one step closer to a potential zero/low allocation implementation suitable for no_std scenarios.
