### ISSUE TITLE
Implement Light, Small, and Full ACK as defined by the spec

### ISSUE THREAD

**Issue by robertream** [russelltg/srt-rs#110]
See: https://datatracker.ietf.org/doc/html/draft-sharabayko-mops-srt-00#section-3.2.3

There are several types of ACK packets:

A Full ACK control packet is sent every 10 ms and has all the
fields of Figure 10.

A Lite ACK control packet includes only the Last Acknowledged
Packet Sequence Number field. The Type-specific Information field
should be set to 0.

A Small ACK includes the fields up to and including the Available
Buffer Size field. The Type-specific Information field should be
set to 0.

The sender only acknowledges the receipt of Full ACK packets (see
ACKACK).

The Lite ACK and Small ACK packets are used in cases when the
receiver should acknowledge received data packets more often than
every 10 ms. This is usually needed at high data rates. It is up to
the receiver to decide the condition and the type of ACK packet to
send (Lite or Small). The recommendation is to send a Lite ACK for
every 64 packets received.

**Comment by robertream** [comment]
@russelltg wow, that was quick!
I don't think AckSeqNumber ought to be a wrapper for i32. The value 0 has meaning. It should be NonZeroU32. I think the spec is unclear on this, but it should probably be a modulo number too, like the other sequence numbers in the spec. Did you see my pull request?

**Comment by russelltg** [comment]
I somehow didn't get an email about it, oops! Looking right now. 

I probably agree that it should be NonZeroU32.

**Comment by robertream** [comment]
The problem I had with NonZeroU32 is that doing increment and modulo math with it required either unsafe code or an unwrap, which felt gross. So I left it as u32.

**Comment by russelltg** [comment]
I think that's alright. 

The spec seems silent on wrapping behavior, but at 100Hz 32-bit values only wrap every 30 years, not something I'm terribly concerned about.

**Comment by robertream** [comment]
Fair point, I hadn't calculated that.

**Comment by robertream** [comment]
Also, I think SeqNumber should be changed to PacketSeqNumber, the spec differentiates between ACK Sequence Number and Packet Sequence Number. I'd also be fine with getting rid of the Seq so PacketNumber and AckNumber.

**Comment by russelltg** [comment]
I'm okay with that. Ack number is the sequence number that the ack reconginzes, so I think we should keep the Seq's.
