### ISSUE TITLE
Is there a way to connect and read from the connection without async ? 

### ISSUE THREAD

**Issue by Lighty0410** [russelltg/srt-rs#113]
Hello everyone! 
There's a useful example of how to connect&read from the socket using async - https://github.com/russelltg/srt-rs/blob/master/srt-tokio/examples/receiver.rs. 
But is there a way to do all the same things without the async environment using srt-protocol only ? If so, how can i do this ? 
Thanks in advance.

**Comment by russelltg** [comment]
Yes there is! You'll have to write some code of course.....

There are two good examples for you to use:

`srt-protocol/tests/lossy_deterministic.rs`: A test for simulating networks that uses srt-protocol directly
`srt-tokio/src/socket.rs`: The tokio socket implementation

If you tell me your usecase maybe I can help you more.

**Comment by russelltg** [comment]
Closing this as I believe I have answered the question--feel free to reopen if that is not the case
