### ISSUE TITLE
Buffer size is constantly growing while receiving packets (memory leak or... ?). 

### ISSUE THREAD

**Issue by Lighty0410** [russelltg/srt-rs#114]
Hey everyone So i fired the [example](https://github.com/russelltg/srt-rs/blob/master/srt-tokio/examples/receiver.rs) for 1hour 15 minutes. And the problem is the internal vector is constantly growing (with some valgrind examples below) causing more and more memory usage over time.
I used the latest version of the repo - `srt-tokio = {git = "https://github.com/russelltg/srt-rs", branch = "master"}` . The way i received packets: 
1) Run  srt-live-transmit udp://:1234 srt://:4201 -v
2) Run ffmpeg -re -stream_loop -1 -i video.ts -c copy -f mpegts "udp://127.0.0.1:1234?pkt_size=1316"
3) valgrind --tool=massif ./my_proj (copy and paste of the example above) 
Results: 
First project (copy and paste from the [example](https://github.com/russelltg/srt-rs/blob/master/srt-tokio/examples/receiver.rs) ): 

![Proj1](https://i.imgur.com/irWJ7tH.png)
![Proj1](https://i.imgur.com/cvteue7.png)

Second project (there are some ffmpeg allocations involved but they work fine, don't mind them): 

![Proj2](https://i.imgur.com/IbkRRI5.png)
![Proj2](https://i.imgur.com/JyNrEY8.png)

So there are a couple of questions: 
1) Is such behavior expected ? If so when the `vec` will stop growing ? 
2) Is it useful to use `srt_socket.flush().await.unwrap();` to prevent such behavior ? 
Thanks in advance!

**Comment by Lighty0410** [comment]
Tried to trace the root of the issues i faced. 
And so far there are multiple vecs that are constantly growing and never reallocate with the default capacity/stop growing - 
1) Receiver.packet_history_window,
2) Receiver.packet_pair_window, 
3) Receiver.ack_history_window, 
4) Receiver.loss_list

Idk, if there are any other leaks. But there are the ones i found.

**Comment by russelltg** [comment]
Hey thanks for the triage! This tracked in #40, but thanks for taking a stab
