### ISSUE TITLE
Release new version on crates.io

### ISSUE THREAD

**Issue by BarthesSimpson** [russelltg/srt-rs#183]
Would you consider releasing an updated version on crates.io? The published version is quite old.

**Comment by russelltg** [comment]
@MarcAntoine-Arnaud is actually the one who published it in the first place....It would be great if he could invite me to be another owner of the related crates? Or at least publish a new version....

**Comment by nipierre** [comment]
Hi, I'm in direct contact with him so I'll speed things up.
Also, I will push a suggestion of crate push from tag in the CI, as we discussed some time ago.

**Comment by MarcAntoine-Arnaud** [comment]
Hello,
I have invited you @russelltg.
But you've to manage versions in crates as v0.3.0 are already released.

Don't hesitate if you need some help.

**Comment by BarthesSimpson** [comment]
Thanks for the fast response and action!

**Comment by nipierre** [comment]
Now that the workflow is merged, can anyone test the release mechanism with a 0.4.0 ? :-)

**Comment by russelltg** [comment]
After some minor fixes to the publishing logic, 0.4.1 (0.4.0 had a problem) is published!
