### ISSUE TITLE
Threading

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [russelltg/srt-rs#34]
Hello,

I'm starting using the library, what do you mean by `The reference implementation of SRT requires 3 threads per sender and 5 threads per receiver` ?

Can you provide simple examples in a folder `examples` ? it can be run using `cargo run --example sender` for a filename `sender.rs`
It can send fake data and implement also a demo example.

**Comment by MarcAntoine-Arnaud** [comment]
If I change the data size to >8000 bytes the sender stop avec 113 packets.
Is it linked to the threading part ?

**Comment by russelltg** [comment]
Heh, I wrote that threading thing a while ago...I remember doing some sort of benchmark where i spun up a lot of senders and receviers (I would hope in the same process, or else it wouldn't be apples to apples, although I cannot say that for sure) and saw how many OS threads, and that was the number I got. 

The main thing I was trying to show by that (and should likely be clarified) is that this implementation uses rust async tasks, which are sort of like greenthreads, that are much lighter than os threads so it in theory should have better performance with thousands of connections, not that that's a huge concern for SRT anyways.

Thanks for the examples PR, there are some small examples in doc comments but i should write more of them in general. The tests are a decent place to start as well.

> change data size to >8000 bytes

What do you mean? Could you give a code example?

**Comment by MarcAntoine-Arnaud** [comment]
Yes `async` is just awesome !

In the example, [here](https://github.com/media-io/srt-rs/blob/add_examples/examples/sender.rs#L18) I have changed to 8000 and it not works as mentionned.

**Comment by russelltg** [comment]
Oh wow that's surprising, considering I have a test that's pretty much exactly that (message_splitting) except it's 500k and not 8k. 

I'll debug it tonight, thanks a ton for the report.

**Comment by russelltg** [comment]
I'm going to close this, I've commented on your PR. Feel free to repoen if you have more questions, or open a new issue.
