### ISSUE TITLE
Write multiplex example

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [russelltg/srt-rs#36]
Hello,

I'm researching to send a stream to multiple listeners.
Is it possible with SRT protocol ?

Or does I need to send for each one on a different port ?

Thanks
Marc-Antoine

**Comment by russelltg** [comment]
Nope! Totally possible, and actually already implemented here (could be buggy, the testing is in general limited as of now). 

Look at `SrtSocketBuilder::build_multiplexed`, if you use that instead of build, you can connect as many clients to it as you like.

**Comment by russelltg** [comment]
I'll keep this issue around as a reminder to write an example for this.

**Comment by MarcAntoine-Arnaud** [comment]
I'll try to add an example around that ! awesome news !!!
Thank you

**Comment by belltoy** [comment]
@russelltg I wrote an example for this, in #56
