### ISSUE TITLE
Test default CC implementation

### ISSUE THREAD

**Issue by russelltg** [russelltg/srt-rs#5]
I'm pretty sure  it's wrong, wayyy too slow.

Ways to test this: sending big files over lossy connections? Should compare to reference UDT?

Also could be possible it's not worth implementing and this repo should be pure SRT.

**Comment by robertream** [comment]
@russelltg I have a pull request that implements Live CC, I don't think File is worth it. You should close this.

**Comment by russelltg** [comment]
(will close when we merge the PR)
