### ISSUE TITLE
Exposing streamid

### ISSUE THREAD

**Issue by fkaa** [russelltg/srt-rs#65]
Would it be possible to expose the `streamid` described [here](https://github.com/Haivision/srt/blob/master/docs/AccessControl.md)? I see that it's already getting parsed in the handshake, but I'm not really sure how the best way to expose it would be. AFAICT it only arrives after a listener socket has received a connection.

**Comment by russelltg** [comment]
This should be fixed now, see the `accesscontrol_server` and `accesscontrol_client` examples. Re-open this if you have any questions/issues.
