### ISSUE TITLE
ipv6 support 

### ISSUE THREAD

**Issue by lu-zero** [russelltg/srt-rs#69]
I saw that the current master has at least a TODO about it in `srt-protocol/src/packet/control.rs`:
``` rust
                // TODO: this is probably really wrong, so fix it
                let peer_addr = if ip_buf[4..] == [0; 12][..] {
                    IpAddr::from(Ipv4Addr::new(ip_buf[3], ip_buf[2], ip_buf[1], ip_buf[0]))
                } else {
                    IpAddr::from(ip_buf)
                };
``` 

Is there anything else to be addressed?

**Comment by russelltg** [comment]
Yeah, so I'm pretty sure the "correct" way to do this the packet needs to know if it's being send/received from an ipv6 socket, so it will require a bit of reorganization (right now it just "guesses" by the lower bytes in the ipv6 address)

**Comment by russelltg** [comment]
For anyone who would want to take this issue:

- [ ] Allow packet parsing to know if it's IPV4 or IPV6 (or, alternatively, just store the IP buffer in the packet and rely on the implementation to know), I'm willing to be convinced either way. I'd prefer the first if it's not too messy, to keep the packet structure "pure"
- [ ] Add tests using IPv6

**Comment by lu-zero** [comment]
I can confirm that the it seem so:
``` c++
// in srtcore/core.cpp
    CIPAddress::pton((m_parent->m_SelfAddr), m_piSelfIP, agent.family(), peer);
```
