### ISSUE TITLE
Implement TSBPD more precisely

### ISSUE THREAD

**Issue by russelltg** [russelltg/srt-rs#72]
It's roughly correct now, but it needs to be RTT_0/2 + latency, which it isn't exactly. See

https://tools.ietf.org/html/draft-sharabayko-mops-srt-00#section-4.5

**Comment by robertream** [comment]
what do you think is the delta between what we have and what is in the spec?
are we not using a TSBPD derived from the handshake algorithm?

**Comment by russelltg** [comment]
We are using a TSBPD derived form the handshake algo, I haven't looked closely at how the start times for the sockets are decided--it could already be correct but i'm not really sure--the hope is we call `Instant::now` on each socket exactly one rtt/2 from each other. I'm not sure that that's true

**Comment by russelltg** [comment]
I believe this is now implemented properly, see the precise_ts0 test
