### ISSUE TITLE
Receiver.packet_history_window memory leak

### ISSUE THREAD

**Issue by dholroyd** [russelltg/srt-rs#88]
Data is pushed into the `Receiver.packet_history_window` here,

https://github.com/russelltg/srt-rs/blob/d5120eb461bbc2643aa7aeb38e65b0bd84a4165f/srt-protocol/src/protocol/receiver/mod.rs#L491

However there doesn't seem to be any code to remove items from this `Vec`, so we eventually run out of memory.

**Comment by russelltg** [comment]
Duplicate #40 

Thanks for the report!
